spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: postgres
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5432/spring_batch
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
  batch:
    job:
      names: ${job.name:NONE}
    jdbc:
      initialize-schema: always
#      enabled: true
#    jdbc:
#      initialize-schema: always
#      table-prefix: SYSTEM_
